---
version: '2'

services:
  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    hostname: sabnzbd
    ports:
      - "8080:8080"
    volumes:
      - ${CONFIG}/sabnzbd:/config
      - ${DOWNLOAD}/complete:/complete 
      - ${DOWNLOAD}/incomplete:/incomplete-downloads
      - ${DOWNLOAD}/watch:/watch
    environment:
      - PGID
      - PUID
      - TZ
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    ports:
      - "8989:8989"
    volumes:
      - ${CONFIG}/sonarr:/config
      - ${DOWNLOAD}/complete:/downloads
      - ${DOWNLOAD}/incomplete:/incomplete-downloads
      - ${DATA}/tv:/tv
      - ${DATA}/anime:/anime
    environment:
      - PGID
      - PUID
      - TZ
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    ports:
      - "7878:7878"
    volumes:
      - ${CONFIG}/radarr:/config
      - ${DOWNLOAD}/complete:/downloads
      - ${DATA}/movies:/movies
    environment:
      - PGID
      - PUID
      - TZ
    restart: unless-stopped

  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    hostname: lidarr
    ports:
      - "8686:8686"
    volumes:
      - ${CONFIG}/lidarr:/config
      - /etc/localtime:/etc/localtime:ro
      - ${DOWNLOAD}/complete:/downloads
      - ${DATA}/music:/music
    environment:
      - PGID
      - PUID
    restart: unless-stopped

  lazylibrarian:
    image: linuxserver/lazylibrarian:latest
    container_name: lazylibrarian
    hostname: lazylibrarian
    ports:
      - "5299:5299"
    volumes:
      - ${CONFIG}/lazylibrarian:/config
      - ${DOWNLOAD}/complete:/downloads
      - ${DATA}/books:/books
    environment:
      - PGID
      - PUID
      - TZ
    restart: unless-stopped

  mylar:
    image: linuxserver/mylar:latest
    container_name: mylar
    hostname: mylar
    ports:
      - "8090:8090"
    volumes:
      - ${CONFIG}/mylar:/config
      - ${DOWNLOAD}/complete:/downloads
      - ${DATA}/comics:/comics
    environment:
      - PGID
      - PUID
      - TZ
    restart: unless-stopped

  nzbhydra:
    image: linuxserver/hydra2:latest
    container_name: nzbhydra
    hostname: nzbhydra
    ports:
      - "5076:5076"
    volumes:
      - ${CONFIG}/nzbhydra2:/config
      - ${DOWNLOAD}/complete:/downloads
    environment:
      - PGID
      - PUID
      - TZ
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    hostname: plex
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "1900:1900/udp"
    volumes:
      - ${CONFIG}/plex:/config
      - ${DATA}/tv:/media/tv
      - ${DATA}/movies:/media/movies
      - ${DATA}/music:/media/music
      - ${DATA}/anime:/media/anime
    environment:
      - PGID
      - PUID
      - TZ
      - VERSION=latest
    restart: unless-stopped

  plexpy:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    hostname: tautulli
    ports:
      - "8181:8181"
    volumes:
      - ${CONFIG}/plexpy:/config
      - ${CONFIG}/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
    environment:
      - PGID
      - PUID
      - TZ
    restart: unless-stopped

  usenet-agent:
    image: cxkoda/usenet-agent:latest
    container_name: usenet-agent
    hostname: usenet-agent
    volumes:
      - ${CONFIG}/usenet-agent:/config
    environment:
      - PGID
      - PUID
      - TZ
    restart: unless-stopped

  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    volumes:
      - ${CONFIG}/jellyfin:/config
      - ${DATA}/tv:/data/tvshows
      - ${DATA}/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920
    environment:
      - PUID
      - PGID
      - TZ
    restart: unless-stopped